"""Tests for src.rb.targets — compute_targets (raw-stat targets).

The standard "all targets present / identity / NaN-fill / no-mutation /
fumbles-lost sum / big game" tests are generated by
``tests.shared.parameterized_targets``. RB-specific tests (aggregator
PPR sanity check, nflverse `fantasy_points_ppr` drift warning) stay in
this file.
"""

import pytest

from src.rb.config import POSITION_CONFIG
from src.rb.targets import compute_targets
from tests.rb.conftest import _build_row as _make_row
from tests.shared.parameterized_targets import (
    PositionTargetSpec,
    install_parameterized_targets,
)

TARGETS = POSITION_CONFIG.targets


install_parameterized_targets(
    globals(),
    PositionTargetSpec(
        position="RB",
        compute_targets=compute_targets,
        targets=TARGETS,
        make_row=_make_row,
        nan_row_columns=(
            "rushing_yards",
            "receiving_yards",
            "receptions",
            "rushing_tds",
            "receiving_tds",
            "sack_fumbles_lost",
            "rushing_fumbles_lost",
            "receiving_fumbles_lost",
            "passing_yards",
            "passing_tds",
            "interceptions",
        ),
        has_fumbles_lost=True,
        identity_targets=(
            ("rushing_yards", 123),
            ("receiving_yards", 57),
            ("receptions", 7),
            ("rushing_tds", 2),
            ("receiving_tds", 3),
        ),
        big_game_overrides={
            "rushing_yards": 300,
            "receiving_yards": 200,
            "receptions": 10,
            "rushing_tds": 4,
            "receiving_tds": 2,
        },
    ),
)


# ---------------------------------------------------------------------------
# RB-specific tests — aggregator PPR sanity, nflverse drift warning
# ---------------------------------------------------------------------------


@pytest.mark.unit
class TestComputeRBTargets:
    def test_aggregator_matches_fantasy_points_check(self, make_rb_row):
        """fantasy_points_check (via aggregator) matches manual raw-stat scoring (PPR)."""
        df = make_rb_row(
            rushing_yards=80,
            receiving_yards=40,
            receptions=4,
            rushing_tds=1,
            receiving_tds=0,
            rushing_fumbles_lost=1,
        )
        result = compute_targets(df)
        expected = 80 * 0.1 + 40 * 0.1 + 4 * 1.0 + 1 * 6 + 0 * 6 + 1 * -2
        assert pytest.approx(result["fantasy_points_check"].iloc[0]) == expected

    def test_nflverse_ppr_mismatch_warning(self, make_rb_row, capsys):
        """If `fantasy_points_ppr` (nflverse) drifts from `fantasy_points` by
        more than 0.5 pt on any row, compute_targets prints an INFO line so
        the discrepancy is visible during pipeline runs."""
        df = make_rb_row(rushing_yards=80, receiving_yards=40, receptions=4, rushing_tds=1)
        df["fantasy_points_ppr"] = df["fantasy_points"] - 1.0
        compute_targets(df)
        captured = capsys.readouterr().out
        assert "differ from nflverse fantasy_points_ppr" in captured
