"""Tests for src.rb.features — _compute_features and fill_nans.

The standard "all features created", "first-week NaN", "zero-input no inf",
"multi-season independence", and ``fill_nans`` test cases are generated by
``tests.shared.parameterized_features``. RB-specific tests (temp-column
cleanup, per-rate yards/carry computation, team carry-share assertions,
all-NaN training-set fill) stay in this file.
"""

import numpy as np
import pandas as pd
import pytest

from src.rb.features import _compute_features, fill_nans
from tests.rb.conftest import _build_player_games
from tests.shared.parameterized_features import (
    PositionFeatureSpec,
    install_parameterized_features,
)

FEATURE_COLS = [
    "yards_per_carry_L3",
    "reception_rate_L3",
    "team_rb_carry_share_L3",
    "team_rb_target_share_L3",
    "rushing_epa_per_attempt_L3",
    "rushing_first_down_rate_L3",
    "receiving_first_down_rate_L3",
    "yac_per_reception_L3",
    "receiving_epa_per_target_L3",
    "air_yards_per_target_L3",
]


install_parameterized_features(
    globals(),
    PositionFeatureSpec(
        position="RB",
        compute_features=_compute_features,
        fill_nans=fill_nans,
        feature_cols=FEATURE_COLS,
        make_player_games=_build_player_games,
        first_week_check_features=("yards_per_carry_L3", "reception_rate_L3"),
        zero_input_overrides={
            "carries": {"carries": 0, "rushing_yards": 0},
            "targets": {"targets": 0, "receptions": 0},
            "receptions": {"receptions": 0, "receiving_yards_after_catch": 0},
        },
        zero_input_features={
            "carries": ["yards_per_carry_L3"],
            "targets": ["reception_rate_L3"],
            "receptions": ["yac_per_reception_L3"],
        },
        seasons_check_feature="yards_per_carry_L3",
        seasons_factory_kwargs=(
            {"carries": 20, "rushing_yards": 100},
            {"carries": 5, "rushing_yards": 20},
        ),
    ),
)


@pytest.mark.unit
class TestComputeRBSpecific:
    """RB-specific tests (temp-column hygiene, per-rate computation,
    team-share arithmetic). These don't generalise to the other positions
    and stay in this file.
    """

    def test_no_temp_columns_remain(self, make_player_games):
        """Temporary columns (_raw_weighted_opps, etc.) should be cleaned up."""
        df = make_player_games()
        _compute_features(df)
        temp_cols = [c for c in df.columns if c.startswith("_")]
        assert temp_cols == [], f"Temp columns left: {temp_cols}"

    def test_zero_carries_zero_yards_per_carry(self, make_player_games):
        """Player with 0 carries: yards_per_carry_L3 should also be 0 (in addition to non-inf)."""
        df = make_player_games(n_weeks=4, carries=0, rushing_yards=0)
        _compute_features(df)
        assert (df["yards_per_carry_L3"].fillna(0) == 0).all()

    def test_yards_per_carry_computation(self, make_player_games):
        """Check yards_per_carry_L3 for constant carries/yards."""
        df = make_player_games(n_weeks=5, carries=10, rushing_yards=50)
        _compute_features(df)
        # Week 3 (index 2): shift sees weeks 1,2; rolling(3,min_periods=1) sums [50,50]=100 yds / 20 carries = 5.0
        week3 = df[df["week"] == 3]
        assert pytest.approx(week3["yards_per_carry_L3"].iloc[0], abs=0.01) == 5.0

    def test_team_carry_share_single_player(self, make_player_games):
        """Solo RB on team should have carry share of 1.0."""
        df = make_player_games(n_weeks=5, carries=15, recent_team="KC")
        _compute_features(df)
        # After enough history, share should be 1.0 (only RB on team)
        later_weeks = df[df["week"] >= 3]
        shares = later_weeks["team_rb_carry_share_L3"]
        valid = shares.dropna()
        if len(valid) > 0:
            assert (valid <= 1.01).all()  # should be ~1.0

    def test_team_carry_share_two_players(self, make_player_games):
        """Two RBs on same team split carries."""
        p1 = make_player_games("P1", n_weeks=5, carries=10, targets=3, recent_team="KC")
        p2 = make_player_games("P2", n_weeks=5, carries=10, targets=3, recent_team="KC")
        df = pd.concat([p1, p2], ignore_index=True)
        _compute_features(df)
        # Each player should have ~0.5 carry share after history builds up
        later = df[(df["week"] >= 3) & (df["player_id"] == "P1")]
        shares = later["team_rb_carry_share_L3"].dropna()
        if len(shares) > 0:
            assert all(0.4 <= s <= 0.6 for s in shares)


@pytest.mark.unit
class TestFillRBNansSpecific:
    """RB-specific NaN-fill behaviour: all-NaN training column must emit a
    visible warning rather than silently zero (regression for the bug fixed
    in TODO.md / `fill_nans_with_train_means`)."""

    def test_all_nan_train_fills_with_zero(self, make_splits, capsys):
        """If training set is all NaN, train_mean is NaN; previously the fill
        was a silent no-op and the catch-all `.fillna(0)` in
        `build_position_features` masked the failure. The hardened
        `fill_nans_with_train_means` now substitutes 0 explicitly and prints
        a warning so the silent zero-feature is visible."""
        train, val, test = make_splits(
            [np.nan, np.nan],
            [np.nan],
            [np.nan],
        )
        train, val, test = fill_nans(train, val, test, ["feat1"])
        assert val["feat1"].iloc[0] == 0.0
        assert test["feat1"].iloc[0] == 0.0
        captured = capsys.readouterr().out
        assert "feat1" in captured
        assert "entirely NaN in training" in captured
