"""Tests for src.wr.features — _compute_features and fill_nans.

The standard "all features created", "first-week NaN", "zero-input no inf",
"multi-season independence", and ``fill_nans`` test cases are generated by
``tests.shared.parameterized_features``. WR-specific tests (per-rate
yards/reception, yards/target, air-yards/target computation, team
target-share assertions) stay in this file.
"""

import numpy as np
import pandas as pd
import pytest

from src.wr.config import POSITION_CONFIG
from src.wr.features import _compute_features, add_specific_features, fill_nans
from tests.shared.parameterized_features import (
    PositionFeatureSpec,
    install_parameterized_features,
)
from tests.wr.conftest import make_wr_player_games

SPECIFIC_FEATURES = POSITION_CONFIG.specific_features


install_parameterized_features(
    globals(),
    PositionFeatureSpec(
        position="WR",
        compute_features=_compute_features,
        fill_nans=fill_nans,
        feature_cols=SPECIFIC_FEATURES,
        make_player_games=make_wr_player_games,
        first_week_check_features=("yards_per_reception_L3", "reception_rate_L3"),
        zero_input_overrides={
            "targets": {
                "targets": 0,
                "receptions": 0,
                "receiving_yards": 0,
                "receiving_air_yards": 0,
                "receiving_yards_after_catch": 0,
                "receiving_epa": 0,
                "receiving_first_downs": 0,
            },
            "receptions_yac": {
                "receptions": 0,
                "receiving_yards_after_catch": 0,
                "receiving_first_downs": 0,
                "receiving_yards": 0,
            },
        },
        zero_input_features={
            "targets": [
                "yards_per_target_L3",
                "reception_rate_L3",
                "air_yards_per_target_L3",
                "receiving_epa_per_target_L3",
            ],
            "receptions_yac": ["yac_per_reception_L3", "receiving_first_down_rate_L3"],
        },
        seasons_check_feature="yards_per_target_L3",
        seasons_factory_kwargs=(
            {"targets": 12, "receiving_yards": 120},
            {"targets": 4, "receiving_yards": 30},
        ),
    ),
)


@pytest.mark.unit
class TestComputeWRRates:
    """WR-specific per-rate computation and team-target-share tests. Each
    asserts the exact rolling-window numeric value the implementation produces.
    """

    def test_yards_per_reception_computation(self, wr_player_games_factory):
        df = wr_player_games_factory(n_weeks=5, receptions=5, receiving_yards=70)
        _compute_features(df)
        # Week 3: rolling sum of [70, 70] = 140 yds / 10 receptions = 14.0
        week3 = df[df["week"] == 3]
        assert pytest.approx(week3["yards_per_reception_L3"].iloc[0], abs=0.01) == 14.0

    def test_reception_rate_computation(self, wr_player_games_factory):
        df = wr_player_games_factory(n_weeks=5, receptions=5, targets=8)
        _compute_features(df)
        week3 = df[df["week"] == 3]
        # 10 / 16 = 0.625
        assert pytest.approx(week3["reception_rate_L3"].iloc[0], abs=0.01) == 5 / 8

    def test_yards_per_target_computation(self, wr_player_games_factory):
        df = wr_player_games_factory(n_weeks=5, targets=8, receiving_yards=80)
        _compute_features(df)
        week3 = df[df["week"] == 3]
        # 160 / 16 = 10.0
        assert pytest.approx(week3["yards_per_target_L3"].iloc[0], abs=0.01) == 10.0

    def test_air_yards_per_target_computation(self, wr_player_games_factory):
        df = wr_player_games_factory(n_weeks=5, targets=8, receiving_air_yards=100)
        _compute_features(df)
        week3 = df[df["week"] == 3]
        # 200 / 16 = 12.5
        assert pytest.approx(week3["air_yards_per_target_L3"].iloc[0], abs=0.01) == 12.5

    def test_team_target_share_single_player(self, wr_player_games_factory):
        """Solo WR on team should have target share close to 1.0."""
        df = wr_player_games_factory(n_weeks=5, targets=8, recent_team="KC")
        _compute_features(df)
        later = df[df["week"] >= 3]
        shares = later["team_wr_target_share_L3"].dropna()
        # Why: rolling-3 share is defined from week 3 onward (3 weeks >= 3 in a 5-week run)
        assert len(shares) == 3
        # Why: solo WR -> share == 1.0; 1.01 ceiling absorbs float rounding
        assert (shares <= 1.01).all()

    def test_team_target_share_two_players(self, wr_player_games_factory):
        """Two WRs should roughly split target share."""
        p1 = wr_player_games_factory("W1", n_weeks=5, targets=8, recent_team="KC")
        p2 = wr_player_games_factory("W2", n_weeks=5, targets=8, recent_team="KC")
        df = pd.concat([p1, p2], ignore_index=True)
        _compute_features(df)
        later = df[(df["week"] >= 3) & (df["player_id"] == "W1")]
        shares = later["team_wr_target_share_L3"].dropna()
        assert len(shares) == 3
        assert all(0.4 <= s <= 0.6 for s in shares)

    def test_team_target_share_stint_aware_on_trade(self):
        """#674: the 3-week team-WR-target-share denominator must reset on a
        mid-season trade, not mix the old and new team's WR-target volume.

        WR_A plays weeks 1-4 on KC alongside teammate WR_B (each 8 targets →
        KC WR total = 16/week, WR_A share ≈ 0.5), then is traded to SF for
        weeks 5-7 where he's the lone WR (SF WR total = 8/week, share = 1.0).
        At week 7 the rolling window (shift(1) → weeks 5,6) lies entirely
        inside the SF stint, so the stint-aware share is exactly 1.0. The old
        ``player×season`` grouping spanned the trade (window weeks 4,5,6 →
        player 24 / team 16+8+8=32 = 0.75), so this value separates the fix
        from the bug.
        """
        wr_a_kc = make_wr_player_games("WR_A", season=2023, n_weeks=4, targets=8, recent_team="KC")
        wr_a_sf = make_wr_player_games("WR_A", season=2023, n_weeks=3, targets=8, recent_team="SF")
        wr_a_sf["week"] = [5, 6, 7]
        wr_b_kc = make_wr_player_games("WR_B", season=2023, n_weeks=4, targets=8, recent_team="KC")
        df = pd.concat([wr_a_kc, wr_a_sf, wr_b_kc], ignore_index=True)
        _compute_features(df)

        a = df[df["player_id"] == "WR_A"].sort_values("week")
        wk7 = a[a["week"] == 7]["team_wr_target_share_L3"].iloc[0]
        # Stint-aware: window {5,6} fully inside the SF stint → 16/16 = 1.0.
        # (A non-stint denominator would give 0.75, mixing KC's wk4 total.)
        assert pytest.approx(wk7, abs=1e-9) == 1.0


@pytest.mark.unit
class TestFullTrainTeamTotals:
    """#531: the WR team-target-share denominator must be computed over the
    pre-MIN_GAMES-filter train so a surviving WR's share is measured against
    the FULL team — including teammates the train filter drops — matching what
    the (unfiltered) val/test splits see."""

    def test_full_train_denominator_includes_dropped_players(self):
        """WR_A survives the filter; WR_B (sub-min-games) is dropped from the
        filtered train but present in ``full_train``. With ``full_train`` the
        rolling team-target share for WR_A is 0.5 in the weeks whose 3-game
        window lies inside WR_B's tenure (10 / (10 + 10)); without it the
        denominator undercounts and the share reads 1.0."""
        # MIN_GAMES_PER_SEASON == 6: 7 games survives, 3 games is dropped.
        wr_a = make_wr_player_games("WR_A", season=2023, n_weeks=7, targets=10, recent_team="KC")
        wr_b = make_wr_player_games("WR_B", season=2023, n_weeks=3, targets=10, recent_team="KC")
        full_train = pd.concat([wr_a, wr_b], ignore_index=True)
        filtered_train = full_train[full_train["player_id"] == "WR_A"].copy()
        val = make_wr_player_games("WR_A", season=2024, n_weeks=2, targets=10, recent_team="KC")
        test = make_wr_player_games("WR_A", season=2024, n_weeks=2, targets=10, recent_team="KC")

        # New path — weeks 2-4 roll over windows fully inside WR_B's tenure
        # (wk2←{1}, wk3←{1,2}, wk4←{1,2,3}), so the denominator includes WR_B.
        train_new, _, _ = add_specific_features(
            filtered_train.copy(), val.copy(), test.copy(), full_train=full_train.copy()
        )
        a_new = train_new[train_new["player_id"] == "WR_A"].sort_values("week")
        assert set(a_new["week"]) == set(range(1, 8))
        wk234 = a_new[a_new["week"].isin([2, 3, 4])]["team_wr_target_share_L3"].to_numpy()
        np.testing.assert_allclose(wk234, 0.5, atol=1e-9)

        # Old path (full_train=None) — denominator is the filtered train only.
        train_old, _, _ = add_specific_features(filtered_train.copy(), val.copy(), test.copy())
        a_old = train_old[train_old["player_id"] == "WR_A"].sort_values("week")
        wk234_old = a_old[a_old["week"].isin([2, 3, 4])]["team_wr_target_share_L3"].to_numpy()
        np.testing.assert_allclose(wk234_old, 1.0, atol=1e-9)

    def test_full_train_none_is_back_compatible(self):
        """``full_train=None`` reproduces the legacy single-frame behaviour."""
        df = pd.concat(
            [
                make_wr_player_games("W1", n_weeks=5, targets=8, recent_team="KC"),
                make_wr_player_games("W2", n_weeks=5, targets=8, recent_team="KC"),
            ],
            ignore_index=True,
        )
        val = make_wr_player_games("W1", season=2024, n_weeks=2, recent_team="KC")
        test = make_wr_player_games("W1", season=2024, n_weeks=2, recent_team="KC")
        out_default, _, _ = add_specific_features(df.copy(), val.copy(), test.copy())
        out_none, _, _ = add_specific_features(df.copy(), val.copy(), test.copy(), full_train=None)
        pd.testing.assert_frame_equal(out_default, out_none)


@pytest.mark.unit
class TestWRBoomFeatures:
    """Production build of the red-zone / opportunity boom block (A/B +all,
    src/tuning/ab_boom_signals_wr.py). The per-game shares/index feed attention history;
    the L3 rollings feed the whitelist. Byte-identical to the validated A/B injector on
    real splits — this locks the production per-game formulas + leakage-safe rolling
    against a regression the A/B-spec test (which exercises the injector) wouldn't catch.
    """

    def _frame(self) -> pd.DataFrame:
        # KC: WR A (lead, 8 tgt) + WR B (2 tgt), 3 weeks; A redzone_targets 2/0/1.
        rows = []
        for wk, a_rz in zip((1, 2, 3), (2.0, 0.0, 1.0), strict=True):
            for pid, tgt, rec, rz in (("A", 8, 5, a_rz), ("B", 2, 1, 0.0)):
                rows.append(
                    dict(
                        player_id=pid,
                        season=2023,
                        week=wk,
                        recent_team="KC",
                        targets=tgt,
                        carries=0,
                        receptions=rec,
                        receiving_yards=rec * 12,
                        receiving_air_yards=tgt * 10,
                        receiving_yards_after_catch=rec * 5,
                        receiving_epa=1.0,
                        receiving_first_downs=1,
                        redzone_targets=rz,
                        redzone_target_share=0.25 if pid == "A" else 0.0,
                    )  # fmt: skip
                )
        return pd.DataFrame(rows)

    def test_per_game_shares_and_opportunity_index(self):
        df = self._frame()
        _compute_features(df)
        g = df.set_index(["player_id", "week"])
        # WR-scoped team targets = 8 + 2 = 10 → A share 0.8, B share 0.2.
        assert g.loc[("A", 1), "game_target_share"] == pytest.approx(0.8)
        assert g.loc[("B", 1), "game_target_share"] == pytest.approx(0.2)
        # HHI = 0.8² + 0.2² = 0.68 (WR concentration that game).
        assert g.loc[("A", 1), "game_target_hhi"] == pytest.approx(0.68)
        # Weighted opportunity index (carries 0): player 2·8=16 / team 2·10=20 = 0.8.
        assert g.loc[("A", 1), "game_opportunity_index"] == pytest.approx(0.8)

    def test_redzone_rolling_is_leakage_safe(self):
        df = self._frame()
        _compute_features(df)
        a = df[df["player_id"] == "A"].set_index("week")["redzone_targets_L3"]
        assert pd.isna(a.loc[1])  # shift(1): week 1 has no prior game → NaN (fill_nans backfills)
        assert a.loc[2] == pytest.approx(2.0)  # mean(week1=2)
        assert a.loc[3] == pytest.approx(1.0)  # mean(week1=2, week2=0)


@pytest.mark.unit
class TestFillWRNansPriorSeason:
    """#1368: prior_season_mean_catch_rate is whitelisted (INCLUDE_FEATURES
    ["prior_season"]) but absent from _SPECIFIC_FEATURES, so it must be
    carved into the leak-safe train-mean fill — otherwise a rookie /
    no-prior-season WR falls through to build_position_features' catch-all
    .fillna(0), and a raw 0 (vs a ~0.60 league catch rate) maps to a strong
    negative z-score post-scaler. Mirrors the RB fix (#390)."""

    def test_catch_rate_train_mean_filled_not_zero(self):
        train = pd.DataFrame(
            {"feat1": [1.0, 2.0, 3.0], "prior_season_mean_catch_rate": [0.5, 0.7, float("nan")]}
        )
        val = pd.DataFrame({"feat1": [1.5], "prior_season_mean_catch_rate": [float("nan")]})
        test = pd.DataFrame({"feat1": [2.5], "prior_season_mean_catch_rate": [float("nan")]})

        # wr_feature_cols deliberately excludes the prior-season column — the
        # pipeline passes only _SPECIFIC_FEATURES here.
        train, val, test = fill_nans(train, val, test, ["feat1"])

        train_mean = 0.6  # mean of the two non-NaN train rows
        assert pytest.approx(train["prior_season_mean_catch_rate"].iloc[2]) == train_mean
        assert pytest.approx(val["prior_season_mean_catch_rate"].iloc[0]) == train_mean
        assert pytest.approx(test["prior_season_mean_catch_rate"].iloc[0]) == train_mean

    def test_carve_out_wiring_matches_production_config(self):
        """Pin the activation preconditions the carve-out silently depends on:
        the column is whitelisted (so the model consumes it), absent from
        _SPECIFIC_FEATURES (so it needs the carve-out at all), and
        _compute_features emits it under exactly this name — a rename or
        whitelist change must fail HERE, not silently re-zero rookies."""
        from src.wr.features import get_feature_columns

        col = "prior_season_mean_catch_rate"
        assert col in get_feature_columns()
        assert col not in SPECIFIC_FEATURES
        df = make_wr_player_games(n_weeks=3)
        df["prior_season_mean_receptions"] = 3.0
        df["prior_season_mean_targets"] = 5.0
        _compute_features(df)
        assert col in df.columns
        assert df[col].notna().all()
