"""Tests for src.wr.targets - compute_targets (raw-stat targets).

The standard "all targets present / identity / NaN-fill / no-mutation /
fumbles-lost sum / big game" tests are generated by
``tests.shared.parameterized_targets``. WR-specific tests (zero-game
smoke) stay in this file.
"""

import pytest

from src.wr.config import POSITION_CONFIG
from src.wr.targets import compute_targets
from tests.shared.parameterized_targets import (
    PositionTargetSpec,
    install_parameterized_targets,
)
from tests.wr.conftest import _build_wr_row as _make_row

TARGETS = POSITION_CONFIG.targets


install_parameterized_targets(
    globals(),
    PositionTargetSpec(
        position="WR",
        compute_targets=compute_targets,
        targets=TARGETS,
        make_row=_make_row,
        nan_row_columns=(
            "receiving_yards",
            "rushing_yards",
            "receptions",
            "targets",
            "receiving_tds",
            "rushing_tds",
            "sack_fumbles_lost",
            "rushing_fumbles_lost",
            "receiving_fumbles_lost",
            "passing_yards",
            "passing_tds",
            "interceptions",
        ),
        has_fumbles_lost=True,
        identity_targets=(
            ("receiving_tds", 2),
            ("receiving_yards", 95),
            ("receptions", 7),
        ),
        big_game_overrides={
            "receptions": 10,
            "receiving_yards": 150,
            "receiving_tds": 2,
            "rushing_yards": 0,
            "rushing_tds": 0,
        },
    ),
)


# ---------------------------------------------------------------------------
# WR-specific tests — zero game smoke
# ---------------------------------------------------------------------------


@pytest.mark.unit
class TestComputeWRTargets:
    def test_zero_game(self):
        df = _make_row(
            receptions=0,
            receiving_yards=0,
            receiving_tds=0,
            rushing_tds=0,
            rushing_yards=0,
        )
        result = compute_targets(df)
        assert result["receiving_tds"].iloc[0] == 0.0
        assert result["receiving_yards"].iloc[0] == 0.0
        assert result["receptions"].iloc[0] == 0.0
        assert result["fumbles_lost"].iloc[0] == 0.0

    def test_decomposition_allows_trick_play_passing(self, capsys):
        df = _make_row(passing_yards=25, passing_tds=1, interceptions=1)
        compute_targets(df)
        assert "target decomposition discrepancy" not in capsys.readouterr().out
