"""Tests for src.wr.features — _compute_features and fill_nans.

The standard "all features created", "first-week NaN", "zero-input no inf",
"multi-season independence", and ``fill_nans`` test cases are generated by
``tests.shared.parameterized_features``. WR-specific tests (per-rate
yards/reception, yards/target, air-yards/target computation, team
target-share assertions) stay in this file.
"""

import pandas as pd
import pytest

from src.wr.config import POSITION_CONFIG
from src.wr.features import _compute_features, fill_nans
from tests.shared.parameterized_features import (
    PositionFeatureSpec,
    install_parameterized_features,
)

SPECIFIC_FEATURES = POSITION_CONFIG.specific_features


def _make_player_games(
    player_id: str = "W1",
    season: int = 2023,
    n_weeks: int = 5,
    receptions: int = 5,
    targets: int = 8,
    receiving_yards: int = 70,
    receiving_air_yards: int = 100,
    receiving_yards_after_catch: int = 30,
    receiving_epa: float = 2.0,
    receiving_first_downs: int = 3,
    recent_team: str = "KC",
) -> pd.DataFrame:
    """Build a multi-week single-player DataFrame matching WR feature inputs."""
    return pd.DataFrame(
        {
            "player_id": [player_id] * n_weeks,
            "season": [season] * n_weeks,
            "week": list(range(1, n_weeks + 1)),
            "receptions": [receptions] * n_weeks,
            "targets": [targets] * n_weeks,
            "receiving_yards": [receiving_yards] * n_weeks,
            "receiving_air_yards": [receiving_air_yards] * n_weeks,
            "receiving_yards_after_catch": [receiving_yards_after_catch] * n_weeks,
            "receiving_epa": [receiving_epa] * n_weeks,
            "receiving_first_downs": [receiving_first_downs] * n_weeks,
            "recent_team": [recent_team] * n_weeks,
        }
    )


install_parameterized_features(
    globals(),
    PositionFeatureSpec(
        position="WR",
        compute_features=_compute_features,
        fill_nans=fill_nans,
        feature_cols=SPECIFIC_FEATURES,
        make_player_games=_make_player_games,
        first_week_check_features=("yards_per_reception_L3", "reception_rate_L3"),
        zero_input_overrides={
            "targets": {
                "targets": 0,
                "receptions": 0,
                "receiving_yards": 0,
                "receiving_air_yards": 0,
                "receiving_yards_after_catch": 0,
                "receiving_epa": 0,
                "receiving_first_downs": 0,
            },
            "receptions_yac": {
                "receptions": 0,
                "receiving_yards_after_catch": 0,
                "receiving_first_downs": 0,
                "receiving_yards": 0,
            },
        },
        zero_input_features={
            "targets": [
                "yards_per_target_L3",
                "reception_rate_L3",
                "air_yards_per_target_L3",
                "receiving_epa_per_target_L3",
            ],
            "receptions_yac": ["yac_per_reception_L3", "receiving_first_down_rate_L3"],
        },
        seasons_check_feature="yards_per_target_L3",
        seasons_factory_kwargs=(
            {"targets": 12, "receiving_yards": 120},
            {"targets": 4, "receiving_yards": 30},
        ),
    ),
)


@pytest.mark.unit
class TestComputeWRRates:
    """WR-specific per-rate computation and team-target-share tests. Each
    asserts the exact rolling-window numeric value the implementation produces.
    """

    def test_yards_per_reception_computation(self, wr_player_games_factory):
        df = wr_player_games_factory(n_weeks=5, receptions=5, receiving_yards=70)
        _compute_features(df)
        # Week 3: rolling sum of [70, 70] = 140 yds / 10 receptions = 14.0
        week3 = df[df["week"] == 3]
        assert pytest.approx(week3["yards_per_reception_L3"].iloc[0], abs=0.01) == 14.0

    def test_reception_rate_computation(self, wr_player_games_factory):
        df = wr_player_games_factory(n_weeks=5, receptions=5, targets=8)
        _compute_features(df)
        week3 = df[df["week"] == 3]
        # 10 / 16 = 0.625
        assert pytest.approx(week3["reception_rate_L3"].iloc[0], abs=0.01) == 5 / 8

    def test_yards_per_target_computation(self, wr_player_games_factory):
        df = wr_player_games_factory(n_weeks=5, targets=8, receiving_yards=80)
        _compute_features(df)
        week3 = df[df["week"] == 3]
        # 160 / 16 = 10.0
        assert pytest.approx(week3["yards_per_target_L3"].iloc[0], abs=0.01) == 10.0

    def test_air_yards_per_target_computation(self, wr_player_games_factory):
        df = wr_player_games_factory(n_weeks=5, targets=8, receiving_air_yards=100)
        _compute_features(df)
        week3 = df[df["week"] == 3]
        # 200 / 16 = 12.5
        assert pytest.approx(week3["air_yards_per_target_L3"].iloc[0], abs=0.01) == 12.5

    def test_team_target_share_single_player(self, wr_player_games_factory):
        """Solo WR on team should have target share close to 1.0."""
        df = wr_player_games_factory(n_weeks=5, targets=8, recent_team="KC")
        _compute_features(df)
        later = df[df["week"] >= 3]
        shares = later["team_wr_target_share_L3"].dropna()
        # Why: rolling-3 share is defined from week 3 onward (3 weeks >= 3 in a 5-week run)
        assert len(shares) == 3
        # Why: solo WR -> share == 1.0; 1.01 ceiling absorbs float rounding
        assert (shares <= 1.01).all()

    def test_team_target_share_two_players(self, wr_player_games_factory):
        """Two WRs should roughly split target share."""
        p1 = wr_player_games_factory("W1", n_weeks=5, targets=8, recent_team="KC")
        p2 = wr_player_games_factory("W2", n_weeks=5, targets=8, recent_team="KC")
        df = pd.concat([p1, p2], ignore_index=True)
        _compute_features(df)
        later = df[(df["week"] >= 3) & (df["player_id"] == "W1")]
        shares = later["team_wr_target_share_L3"].dropna()
        assert len(shares) == 3
        assert all(0.4 <= s <= 0.6 for s in shares)
