"""Tests for src.qb.features — _compute_features and fill_nans.

The standard "all features created", "first-week NaN", "zero-input no inf",
"multi-season independence", and ``fill_nans`` test cases are generated by
``tests.shared.parameterized_features``. QB-specific tests
(per-rate computation: completion_pct, yards/attempt, td_rate, etc.) stay
in this file.
"""

import pandas as pd
import pytest

from src.qb.features import _compute_features, fill_nans
from tests.shared.parameterized_features import (
    PositionFeatureSpec,
    install_parameterized_features,
)


def _make_player_games(
    player_id="QB1",
    season=2023,
    n_weeks=5,
    completions=20,
    attempts=30,
    passing_yards=250,
    passing_tds=2,
    interceptions=1,
    sacks=2,
    rushing_yards=15,
    passing_epa=5.0,
    passing_air_yards=200,
    carries=3,
    passing_first_downs=10,
    rushing_first_downs=1,
    rushing_epa=1.0,
    passing_yards_after_catch=120,
    sack_yards=14,
):
    """Create a multi-week DataFrame for one QB."""
    return pd.DataFrame(
        {
            "player_id": [player_id] * n_weeks,
            "season": [season] * n_weeks,
            "week": list(range(1, n_weeks + 1)),
            "completions": [completions] * n_weeks,
            "attempts": [attempts] * n_weeks,
            "passing_yards": [passing_yards] * n_weeks,
            "passing_tds": [passing_tds] * n_weeks,
            "interceptions": [interceptions] * n_weeks,
            "sacks": [sacks] * n_weeks,
            "rushing_yards": [rushing_yards] * n_weeks,
            "passing_epa": [passing_epa] * n_weeks,
            "passing_air_yards": [passing_air_yards] * n_weeks,
            "carries": [carries] * n_weeks,
            "passing_first_downs": [passing_first_downs] * n_weeks,
            "rushing_first_downs": [rushing_first_downs] * n_weeks,
            "rushing_epa": [rushing_epa] * n_weeks,
            "passing_yards_after_catch": [passing_yards_after_catch] * n_weeks,
            "sack_yards": [sack_yards] * n_weeks,
        }
    )


FEATURE_COLS = [
    "completion_pct_L3",
    "yards_per_attempt_L3",
    "td_rate_L3",
    "int_rate_L3",
    "sack_rate_L3",
    "qb_rushing_share_L3",
    "passing_epa_per_dropback_L3",
    "deep_ball_rate_L3",
    "pass_first_down_rate_L3",
    "rushing_epa_per_carry_L3",
    "rush_first_down_rate_L3",
    "yac_rate_L3",
    "sack_damage_per_dropback_L3",
]


install_parameterized_features(
    globals(),
    PositionFeatureSpec(
        position="QB",
        compute_features=_compute_features,
        fill_nans=fill_nans,
        feature_cols=FEATURE_COLS,
        make_player_games=_make_player_games,
        first_week_check_features=(
            "completion_pct_L3",
            "yards_per_attempt_L3",
            "td_rate_L3",
        ),
        zero_input_overrides={
            "attempts": {
                "completions": 0,
                "attempts": 0,
                "passing_yards": 0,
                "passing_tds": 0,
                "interceptions": 0,
                "sacks": 0,
                "passing_air_yards": 0,
                "passing_epa": 0,
                "passing_first_downs": 0,
                "passing_yards_after_catch": 0,
                "sack_yards": 0,
            },
            "carries": {
                "carries": 0,
                "rushing_yards": 0,
                "rushing_first_downs": 0,
                "rushing_epa": 0,
            },
            "passing_yards_yac_rate": {"passing_yards": 0, "passing_yards_after_catch": 0},
        },
        zero_input_features={
            # When attempts=0 AND sacks=0, dropbacks=attempts+sacks=0 too,
            # so sack_rate_L3, passing_epa_per_dropback_L3, and
            # sack_damage_per_dropback_L3 (all dropback-denominated) are
            # also part of the 0/0 division contract — the zero-input
            # override below already zeros both ``attempts`` and ``sacks``.
            "attempts": [
                "completion_pct_L3",
                "yards_per_attempt_L3",
                "td_rate_L3",
                "int_rate_L3",
                "sack_rate_L3",
                "deep_ball_rate_L3",
                "pass_first_down_rate_L3",
                "passing_epa_per_dropback_L3",
                "sack_damage_per_dropback_L3",
            ],
            "carries": ["rushing_epa_per_carry_L3", "rush_first_down_rate_L3"],
            "passing_yards_yac_rate": ["yac_rate_L3"],
        },
        seasons_check_feature="yards_per_attempt_L3",
        seasons_factory_kwargs=(
            {"attempts": 30, "passing_yards": 300},
            {"attempts": 20, "passing_yards": 150},
        ),
    ),
)


@pytest.mark.unit
class TestComputeQBRates:
    """QB-specific per-rate computation tests (kept verbatim from the
    pre-refactor suite). Each asserts the exact rolling-window numeric value
    the implementation must produce at week 3 (shift+rolling(3) sees weeks 1-2).
    """

    def test_completion_pct_computation(self):
        """completion_pct_L3 = rolling completions / rolling attempts."""
        df = _make_player_games(n_weeks=5, completions=20, attempts=30)
        _compute_features(df)
        # Week 3 (index 2): shift sees weeks 1,2; rolling(3, sum) = [40]/[60] = 0.667
        week3 = df[df["week"] == 3]
        assert pytest.approx(week3["completion_pct_L3"].iloc[0], abs=0.01) == 20 / 30

    def test_yards_per_attempt_computation(self):
        df = _make_player_games(n_weeks=5, attempts=30, passing_yards=240)
        _compute_features(df)
        week3 = df[df["week"] == 3]
        # 480 / 60 = 8.0
        assert pytest.approx(week3["yards_per_attempt_L3"].iloc[0], abs=0.01) == 8.0

    def test_td_rate_computation(self):
        df = _make_player_games(n_weeks=5, attempts=25, passing_tds=2)
        _compute_features(df)
        week3 = df[df["week"] == 3]
        # 4 / 50 = 0.08
        assert pytest.approx(week3["td_rate_L3"].iloc[0], abs=0.01) == 2 / 25

    def test_int_rate_computation(self):
        df = _make_player_games(n_weeks=5, attempts=25, interceptions=1)
        _compute_features(df)
        week3 = df[df["week"] == 3]
        assert pytest.approx(week3["int_rate_L3"].iloc[0], abs=0.01) == 1 / 25

    def test_sack_rate_computation(self):
        """sack_rate = sacks / (attempts + sacks)."""
        df = _make_player_games(n_weeks=5, attempts=30, sacks=2)
        _compute_features(df)
        week3 = df[df["week"] == 3]
        # sacks=4, dropbacks=60+4=64, rate = 4/64 = 0.0625
        assert pytest.approx(week3["sack_rate_L3"].iloc[0], abs=0.01) == 4 / 64

    def test_rushing_share_computation(self):
        """qb_rushing_share = rush_yds / (pass_yds + rush_yds)."""
        df = _make_player_games(n_weeks=5, passing_yards=300, rushing_yards=30)
        _compute_features(df)
        week3 = df[df["week"] == 3]
        # 60 / 660 = 0.0909
        assert pytest.approx(week3["qb_rushing_share_L3"].iloc[0], abs=0.01) == 60 / 660
