"""Tests for src.qb.targets — compute_targets (raw-stat migration).

The standard "all targets present / identity / NaN-fill / no-mutation /
fumbles-lost sum / big game" tests are generated by
``tests.shared.parameterized_targets``. QB-specific tests (sanity-check
warning behaviour, extra fumbles-lost variants) stay in this file.
"""

import pytest

from src.qb.config import POSITION_CONFIG
from src.qb.targets import compute_targets
from tests.qb.conftest import _build_qb_row as _make_row
from tests.shared.parameterized_targets import (
    PositionTargetSpec,
    install_parameterized_targets,
)

TARGET_COLS = POSITION_CONFIG.targets


install_parameterized_targets(
    globals(),
    PositionTargetSpec(
        position="QB",
        compute_targets=compute_targets,
        targets=TARGET_COLS,
        make_row=_make_row,
        nan_row_columns=(
            "passing_yards",
            "rushing_yards",
            "receiving_yards",
            "receptions",
            "passing_tds",
            "rushing_tds",
            "receiving_tds",
            "interceptions",
            "sack_fumbles_lost",
            "rushing_fumbles_lost",
            "receiving_fumbles_lost",
        ),
        has_fumbles_lost=True,
        identity_targets=(
            ("passing_yards", 317),
            ("rushing_yards", 42),
            ("passing_tds", 3),
            ("rushing_tds", 2),
            ("interceptions", 2),
        ),
        big_game_overrides={
            "passing_yards": 500,
            "passing_tds": 5,
            "rushing_yards": 10,
            "rushing_tds": 0,
            "interceptions": 0,
        },
    ),
)


# ---------------------------------------------------------------------------
# QB-specific tests (sanity-check warnings, extra fumble variant, zero-stat)
# ---------------------------------------------------------------------------


@pytest.mark.unit
class TestComputeQBTargets:
    def test_fumbles_lost_rushing_only(self):
        df = _make_row(sack_fumbles_lost=0, rushing_fumbles_lost=1)
        result = compute_targets(df)
        assert result["fumbles_lost"].iloc[0] == 1

    def test_zero_stat_game(self):
        df = _make_row(
            passing_yards=0,
            rushing_yards=0,
            passing_tds=0,
            rushing_tds=0,
            interceptions=0,
        )
        result = compute_targets(df)
        for col in TARGET_COLS:
            assert result[col].iloc[0] == 0.0

    def test_sanity_check_no_warning_on_clean_input(self, capsys):
        """Aggregator on true targets should reproduce fantasy_points (ex-receiving)."""
        df = _make_row(
            passing_yards=275,
            passing_tds=2,
            rushing_yards=30,
            rushing_tds=1,
            interceptions=1,
        )
        _ = compute_targets(df)
        captured = capsys.readouterr()
        assert "discrepancy" not in captured.out

    def test_sanity_check_warns_on_inconsistent_fantasy_points(self, capsys):
        """If fantasy_points doesn't match the raw stats + receiving, warn."""
        df = _make_row(passing_yards=275, passing_tds=2, fantasy_points=999.0)
        _ = compute_targets(df)
        captured = capsys.readouterr()
        assert "discrepancy" in captured.out
