"""Tests for src.k.targets — 4-head compute_targets.

The standard "all targets present / NaN-fill / no-mutation" tests are
generated by ``tests.shared.parameterized_targets``. K-specific tests
(the 4-head decomposition math, signed fantasy_points formula) stay in
this file.
"""

import pytest

from src.k.config import POSITION_CONFIG
from src.k.targets import compute_targets
from src.shared.aggregate_targets import K_TARGETS
from tests.k.conftest import _build_k_row as _make_row
from tests.shared.parameterized_targets import (
    PositionTargetSpec,
    install_parameterized_targets,
)

TARGETS = POSITION_CONFIG.targets


install_parameterized_targets(
    globals(),
    PositionTargetSpec(
        position="K",
        compute_targets=compute_targets,
        targets=TARGETS,
        make_row=_make_row,
        # K reads only these 4 raw cols; doesn't carry fantasy_points input.
        nan_row_columns=("fg_yards_made", "fg_missed", "pat_made", "pat_missed"),
        # K's all-NaN path produces zero fantasy_points (no tier defaults).
        nan_extra_assertions=(("fantasy_points", 0.0),),
    ),
)


def test_k_targets_match_aggregate_targets_contract():
    """``src.k.config`` targets must stay in sync with ``K_TARGETS`` in
    ``src.shared.aggregate_targets`` — the two are duplicated (config list +
    routing tuple), and ``predictions_to_fantasy_points`` matches K by
    ``set(K_TARGETS)``, so drift would silently misroute K's bespoke scoring.
    """
    assert tuple(POSITION_CONFIG.targets) == tuple(K_TARGETS)


# ---------------------------------------------------------------------------
# K-specific tests — 4-head decomposition math, signed fantasy_points
# ---------------------------------------------------------------------------


@pytest.mark.unit
class TestComputeKTargets:
    def test_fg_yard_points_basic(self):
        """fg_yard_points = fg_yards_made * 0.1."""
        df = _make_row(fg_yards_made=100)
        result = compute_targets(df)
        assert pytest.approx(result["fg_yard_points"].iloc[0]) == 10.0

    def test_fg_yard_points_fractional(self):
        """Distance sums need not be whole multiples of 10."""
        df = _make_row(fg_yards_made=137)
        result = compute_targets(df)
        assert pytest.approx(result["fg_yard_points"].iloc[0]) == 13.7

    def test_fg_yard_points_zero(self):
        df = _make_row(fg_yards_made=0)
        result = compute_targets(df)
        assert pytest.approx(result["fg_yard_points"].iloc[0]) == 0.0

    def test_pat_points(self):
        df = _make_row(pat_made=5)
        result = compute_targets(df)
        assert pytest.approx(result["pat_points"].iloc[0]) == 5.0

    def test_fg_misses_raw_count(self):
        """fg_misses = fg_missed (non-negative raw count)."""
        df = _make_row(fg_missed=2)
        result = compute_targets(df)
        assert pytest.approx(result["fg_misses"].iloc[0]) == 2.0

    def test_xp_misses_raw_count(self):
        """xp_misses = pat_missed (non-negative raw count)."""
        df = _make_row(pat_missed=1)
        result = compute_targets(df)
        assert pytest.approx(result["xp_misses"].iloc[0]) == 1.0

    def test_all_four_heads_non_negative(self):
        """Every head is a non-negative value; sign is applied in fantasy_points."""
        df = _make_row(fg_yards_made=50, pat_made=2, fg_missed=3, pat_missed=1)
        result = compute_targets(df)
        for col in ["fg_yard_points", "pat_points", "fg_misses", "xp_misses"]:
            assert result[col].iloc[0] >= 0, f"{col} should be non-negative"

    def test_fantasy_points_signed_total(self):
        """fantasy_points = fg_yard_points + pat_points - fg_misses - xp_misses."""
        df = _make_row(
            fg_yards_made=100,  # 10.0 pts
            pat_made=3,  # 3.0 pts
            fg_missed=2,  # -2.0
            pat_missed=1,  # -1.0
        )
        result = compute_targets(df)
        # 10.0 + 3.0 - 2.0 - 1.0 = 10.0
        assert pytest.approx(result["fantasy_points"].iloc[0]) == 10.0

    def test_fantasy_points_perfect_game(self):
        """No misses, plenty of yards."""
        df = _make_row(
            fg_yards_made=150,  # 15.0 pts
            pat_made=5,  # 5.0 pts
            fg_missed=0,
            pat_missed=0,
        )
        result = compute_targets(df)
        assert pytest.approx(result["fantasy_points"].iloc[0]) == 20.0

    def test_fantasy_points_all_misses(self):
        """No makes, only misses → negative total."""
        df = _make_row(
            fg_yards_made=0,
            pat_made=0,
            fg_missed=3,
            pat_missed=1,
        )
        result = compute_targets(df)
        # 0 + 0 - 3 - 1 = -4.0
        assert pytest.approx(result["fantasy_points"].iloc[0]) == -4.0
