"""Tests for src.te.features — _compute_features and fill_nans.

The standard "all features created", "first-week NaN", "zero-input no inf",
"multi-season independence", and ``fill_nans`` test cases are generated by
``tests.shared.parameterized_features``. TE-specific tests (per-rate
yards/reception, reception rate, TD/target rate, team target-share
assertions) stay in this file.
"""

import pandas as pd
import pytest

from src.te.features import _compute_features, fill_nans
from tests.shared.parameterized_features import (
    PositionFeatureSpec,
    install_parameterized_features,
)


def _make_player_games(
    player_id="T1",
    season=2023,
    n_weeks=5,
    receptions=4,
    targets=6,
    receiving_yards=55,
    receiving_air_yards=70,
    receiving_yards_after_catch=20,
    receiving_epa=1.5,
    receiving_first_downs=3,
    receiving_tds=1,
    recent_team="KC",
):
    """Build a multi-week single-player DataFrame matching TE feature inputs."""
    return pd.DataFrame(
        {
            "player_id": [player_id] * n_weeks,
            "season": [season] * n_weeks,
            "week": list(range(1, n_weeks + 1)),
            "receptions": [receptions] * n_weeks,
            "targets": [targets] * n_weeks,
            "receiving_yards": [receiving_yards] * n_weeks,
            "receiving_air_yards": [receiving_air_yards] * n_weeks,
            "receiving_yards_after_catch": [receiving_yards_after_catch] * n_weeks,
            "receiving_epa": [receiving_epa] * n_weeks,
            "receiving_first_downs": [receiving_first_downs] * n_weeks,
            "receiving_tds": [receiving_tds] * n_weeks,
            "recent_team": [recent_team] * n_weeks,
        }
    )


FEATURE_COLS = [
    "yards_per_reception_L3",
    "reception_rate_L3",
    "yac_per_reception_L3",
    "team_te_target_share_L3",
    "receiving_epa_per_target_L3",
    "receiving_first_down_rate_L3",
    "air_yards_per_target_L3",
    "td_rate_per_target_L3",
]


install_parameterized_features(
    globals(),
    PositionFeatureSpec(
        position="TE",
        compute_features=_compute_features,
        fill_nans=fill_nans,
        feature_cols=FEATURE_COLS,
        make_player_games=_make_player_games,
        # TE's original suite checks every feature column at week 1; leaving
        # first_week_check_features empty falls back to the full list.
        first_week_check_features=(),
        zero_input_overrides={
            "targets": {
                "targets": 0,
                "receptions": 0,
                "receiving_yards": 0,
                "receiving_air_yards": 0,
                "receiving_yards_after_catch": 0,
                "receiving_epa": 0,
                "receiving_first_downs": 0,
                "receiving_tds": 0,
            },
            "receptions_yac": {
                "receptions": 0,
                "receiving_yards_after_catch": 0,
                "receiving_first_downs": 0,
                "receiving_yards": 0,
            },
        },
        zero_input_features={
            # TE asserts every feature column stays finite when targets=0
            "targets": None,
            "receptions_yac": ["yac_per_reception_L3", "receiving_first_down_rate_L3"],
        },
        seasons_check_feature="yards_per_reception_L3",
        seasons_factory_kwargs=(
            {"targets": 10, "receiving_yards": 100},
            {"targets": 3, "receiving_yards": 25},
        ),
    ),
)


@pytest.mark.unit
class TestComputeTERates:
    """TE-specific per-rate computation and team-target-share tests."""

    def test_yards_per_reception_computation(self):
        df = _make_player_games(n_weeks=5, receptions=4, receiving_yards=48)
        _compute_features(df)
        week3 = df[df["week"] == 3]
        # 96 / 8 = 12.0
        assert pytest.approx(week3["yards_per_reception_L3"].iloc[0], abs=0.01) == 12.0

    def test_reception_rate_computation(self):
        df = _make_player_games(n_weeks=5, receptions=4, targets=6)
        _compute_features(df)
        week3 = df[df["week"] == 3]
        assert pytest.approx(week3["reception_rate_L3"].iloc[0], abs=0.01) == 4 / 6

    def test_td_rate_per_target_computation(self):
        """TE-specific td_rate_per_target_L3."""
        df = _make_player_games(n_weeks=5, receiving_tds=1, targets=6)
        _compute_features(df)
        week3 = df[df["week"] == 3]
        # 2 / 12 = 0.1667
        assert pytest.approx(week3["td_rate_per_target_L3"].iloc[0], abs=0.01) == 1 / 6

    def test_team_target_share_single_player(self):
        df = _make_player_games(n_weeks=5, targets=6, recent_team="KC")
        _compute_features(df)
        later = df[df["week"] >= 3]
        shares = later["team_te_target_share_L3"].dropna()
        assert len(shares) > 0, "no non-NaN shares produced"
        assert (shares <= 1.01).all()

    def test_team_target_share_two_players(self):
        """Two TEs on team split target share."""
        p1 = _make_player_games("T1", n_weeks=5, targets=5, recent_team="KC")
        p2 = _make_player_games("T2", n_weeks=5, targets=5, recent_team="KC")
        df = pd.concat([p1, p2], ignore_index=True)
        _compute_features(df)
        later = df[(df["week"] >= 3) & (df["player_id"] == "T1")]
        shares = later["team_te_target_share_L3"].dropna()
        assert len(shares) > 0, "no non-NaN shares produced"
        assert all(0.4 <= s <= 0.6 for s in shares)
