"""Tests for src.te.targets — compute_targets emits 4 raw-stat columns.

The standard "all targets present / identity / NaN-fill / no-mutation /
fumbles-lost sum / big game" tests are generated by
``tests.shared.parameterized_targets``. TE-specific tests (zero-catch
smoke, aggregator reproducibility, decomposition-discrepancy warning)
stay in this file.
"""

import pytest

from src.te.config import POSITION_CONFIG
from src.te.targets import compute_targets
from tests.shared.parameterized_targets import (
    PositionTargetSpec,
    install_parameterized_targets,
)
from tests.te.conftest import _build_te_row as _make_row

pytestmark = pytest.mark.unit

TARGETS = POSITION_CONFIG.targets


install_parameterized_targets(
    globals(),
    PositionTargetSpec(
        position="TE",
        compute_targets=compute_targets,
        targets=TARGETS,
        make_row=_make_row,
        nan_row_columns=(
            "receiving_yards",
            "rushing_yards",
            "receptions",
            "targets",
            "receiving_tds",
            "rushing_tds",
            "sack_fumbles_lost",
            "rushing_fumbles_lost",
            "receiving_fumbles_lost",
            "passing_yards",
            "passing_tds",
            "interceptions",
        ),
        has_fumbles_lost=True,
        identity_targets=(
            ("receiving_tds", 2),
            ("receiving_yards", 87),
            ("receptions", 6),
        ),
        big_game_overrides={"receptions": 8, "receiving_yards": 120, "receiving_tds": 2},
    ),
)


# ---------------------------------------------------------------------------
# TE-specific tests
# ---------------------------------------------------------------------------


class TestComputeTETargets:
    def test_zero_catch_game(self):
        """TE with 0 catches on blocking-heavy game."""
        df = _make_row(
            receptions=0, receiving_yards=0, receiving_tds=0, rushing_tds=0, rushing_yards=0
        )
        result = compute_targets(df)
        assert result["receiving_tds"].iloc[0] == 0
        assert result["receiving_yards"].iloc[0] == 0
        assert result["receptions"].iloc[0] == 0

    def test_aggregator_reproduces_te_fantasy_points(self):
        """Aggregating the 4 raw targets to fantasy points should match the
        TE-only slice of fantasy_points (no passing/rushing contributions)."""
        from src.shared.aggregate_targets import predictions_to_fantasy_points

        df = _make_row(receptions=6, receiving_yards=60, receiving_tds=1)
        result = compute_targets(df)
        preds = {
            t: result[t].values
            for t in ("receiving_tds", "receiving_yards", "receptions", "fumbles_lost")
        }
        total = predictions_to_fantasy_points("TE", preds, "ppr")
        # 6 rec × 1 + 60 yds × 0.1 + 1 TD × 6 = 18
        assert pytest.approx(total[0]) == 18.0

    def test_decomposition_discrepancy_emits_warning(self, capsys):
        """Rows whose ``fantasy_points`` cannot be reconstructed from the raw
        stats (data corruption upstream) should print a WARNING line."""
        # Why: pin fantasy_points to a value the 4 raw targets can't sum to;
        # _make_row's default stats reconstruct to 17.5 pts, far from 99.0.
        df = _make_row(fantasy_points=99.0)
        compute_targets(df)
        assert "target decomposition discrepancy" in capsys.readouterr().out
