"""Tests for src.te.targets — compute_targets emits 4 raw-stat columns.

The standard "all targets present / identity / NaN-fill / no-mutation /
fumbles-lost sum / big game" tests are generated by
``tests.shared.parameterized_targets``. TE-specific tests (zero-catch
smoke, aggregator reproducibility, decomposition-discrepancy warning)
stay in this file.
"""

import pytest

from src.te.config import POSITION_CONFIG
from src.te.targets import compute_targets
from tests.shared.parameterized_targets import (
    PositionTargetSpec,
    install_parameterized_targets,
)
from tests.te.conftest import _build_te_row as _make_row

pytestmark = pytest.mark.unit

TARGETS = POSITION_CONFIG.targets


install_parameterized_targets(
    globals(),
    PositionTargetSpec(
        position="TE",
        compute_targets=compute_targets,
        targets=TARGETS,
        make_row=_make_row,
        nan_row_columns=(
            "receiving_yards",
            "rushing_yards",
            "receptions",
            "targets",
            "receiving_tds",
            "rushing_tds",
            "sack_fumbles_lost",
            "rushing_fumbles_lost",
            "receiving_fumbles_lost",
            "passing_yards",
            "passing_tds",
            "interceptions",
            # Read by compute_targets' decomposition-discrepancy check (2pt
            # conversions are scored in fantasy_points but aren't TE targets).
            "passing_2pt_conversions",
            "rushing_2pt_conversions",
            "receiving_2pt_conversions",
        ),
        has_fumbles_lost=True,
        identity_targets=(
            ("receiving_tds", 2),
            ("receiving_yards", 87),
            ("receptions", 6),
        ),
        big_game_overrides={"receptions": 8, "receiving_yards": 120, "receiving_tds": 2},
    ),
)


# ---------------------------------------------------------------------------
# TE-specific tests
# ---------------------------------------------------------------------------


class TestComputeTETargets:
    def test_zero_catch_game(self):
        """TE with 0 catches on blocking-heavy game."""
        df = _make_row(
            receptions=0, receiving_yards=0, receiving_tds=0, rushing_tds=0, rushing_yards=0
        )
        result = compute_targets(df)
        assert result["receiving_tds"].iloc[0] == 0
        assert result["receiving_yards"].iloc[0] == 0
        assert result["receptions"].iloc[0] == 0

    def test_aggregator_reproduces_te_fantasy_points(self):
        """Aggregating the 4 raw targets to fantasy points should match the
        TE-only slice of fantasy_points (no passing/rushing contributions)."""
        from src.shared.aggregate_targets import predictions_to_fantasy_points

        df = _make_row(receptions=6, receiving_yards=60, receiving_tds=1)
        result = compute_targets(df)
        preds = {
            t: result[t].values
            for t in ("receiving_tds", "receiving_yards", "receptions", "fumbles_lost")
        }
        total = predictions_to_fantasy_points("TE", preds, "ppr")
        # 6 rec × 1 + 60 yds × 0.1 + 1 TD × 6 = 18
        assert pytest.approx(total[0]) == 18.0

    def test_decomposition_discrepancy_emits_warning(self, capsys):
        """Rows whose ``fantasy_points`` cannot be reconstructed from the raw
        stats (data corruption upstream) should print a WARNING line."""
        # Why: pin fantasy_points to a value the 4 raw targets can't sum to;
        # _make_row's default stats reconstruct to 15.5 PPR pts
        # (4 rec*1 + 55 yds*0.1 + 1 TD*6), far from 99.0.
        df = _make_row(fantasy_points=99.0)
        compute_targets(df)
        assert "target decomposition discrepancy" in capsys.readouterr().out

    def test_no_spurious_warning_on_2pt_conversion_row(self, capsys):
        """#1412: a 2pt conversion adds a flat +2 to the upstream (nflverse)
        fantasy_points column but is not a TE target; the decomposition
        diagnostic must back it out rather than WARN on an exact-2.0
        discrepancy (mirrors the RB back-out shipped for #406)."""
        df = _make_row(receiving_2pt_conversions=1)
        # The builder's auto-computed fantasy_points has no 2pt term; the
        # upstream column includes the conversion, so add it here.
        df["fantasy_points"] = df["fantasy_points"] + 2.0
        compute_targets(df)
        assert "target decomposition discrepancy" not in capsys.readouterr().out
