"""Tests for src.te.features — _compute_features and fill_nans.

The standard "all features created", "first-week NaN", "zero-input no inf",
"multi-season independence", and ``fill_nans`` test cases are generated by
``tests.shared.parameterized_features``. TE-specific tests (per-rate
yards/reception, reception rate, TD/target rate, team target-share
assertions) stay in this file.
"""

import pandas as pd
import pytest

from src.te.features import _compute_features, fill_nans
from tests.shared.parameterized_features import (
    PositionFeatureSpec,
    install_parameterized_features,
)


def _make_player_games(
    player_id="T1",
    season=2023,
    n_weeks=5,
    receptions=4,
    targets=6,
    receiving_yards=55,
    receiving_air_yards=70,
    receiving_yards_after_catch=20,
    receiving_epa=1.5,
    receiving_first_downs=3,
    receiving_tds=1,
    recent_team="KC",
    carries=0,
    redzone_targets=1.0,
    redzone_target_share=0.2,
):
    """Build a multi-week single-player DataFrame matching TE feature inputs."""
    return pd.DataFrame(
        {
            "player_id": [player_id] * n_weeks,
            "season": [season] * n_weeks,
            "week": list(range(1, n_weeks + 1)),
            "receptions": [receptions] * n_weeks,
            "targets": [targets] * n_weeks,
            "receiving_yards": [receiving_yards] * n_weeks,
            "receiving_air_yards": [receiving_air_yards] * n_weeks,
            "receiving_yards_after_catch": [receiving_yards_after_catch] * n_weeks,
            "receiving_epa": [receiving_epa] * n_weeks,
            "receiving_first_downs": [receiving_first_downs] * n_weeks,
            "receiving_tds": [receiving_tds] * n_weeks,
            "recent_team": [recent_team] * n_weeks,
            # Red-zone / opportunity boom-block inputs (#1061 parity).
            "carries": [carries] * n_weeks,
            "redzone_targets": [redzone_targets] * n_weeks,
            "redzone_target_share": [redzone_target_share] * n_weeks,
        }
    )


FEATURE_COLS = [
    "yards_per_reception_L3",
    "reception_rate_L3",
    "yac_per_reception_L3",
    "team_te_target_share_L3",
    "receiving_epa_per_target_L3",
    "receiving_first_down_rate_L3",
    "air_yards_per_target_L3",
    "td_rate_per_target_L3",
    # Red-zone / opportunity boom block (#1061 parity with RB/WR).
    "redzone_targets_L3",
    "redzone_target_share_L3",
    "opportunity_index_L3",
]


install_parameterized_features(
    globals(),
    PositionFeatureSpec(
        position="TE",
        compute_features=_compute_features,
        fill_nans=fill_nans,
        feature_cols=FEATURE_COLS,
        make_player_games=_make_player_games,
        # TE's original suite checks every feature column at week 1; leaving
        # first_week_check_features empty falls back to the full list.
        first_week_check_features=(),
        zero_input_overrides={
            "targets": {
                "targets": 0,
                "receptions": 0,
                "receiving_yards": 0,
                "receiving_air_yards": 0,
                "receiving_yards_after_catch": 0,
                "receiving_epa": 0,
                "receiving_first_downs": 0,
                "receiving_tds": 0,
            },
            "receptions_yac": {
                "receptions": 0,
                "receiving_yards_after_catch": 0,
                "receiving_first_downs": 0,
                "receiving_yards": 0,
            },
        },
        zero_input_features={
            # TE asserts every feature column stays finite when targets=0
            "targets": None,
            "receptions_yac": ["yac_per_reception_L3", "receiving_first_down_rate_L3"],
        },
        seasons_check_feature="yards_per_reception_L3",
        seasons_factory_kwargs=(
            {"targets": 10, "receiving_yards": 100},
            {"targets": 3, "receiving_yards": 25},
        ),
    ),
)


@pytest.mark.unit
class TestComputeTERates:
    """TE-specific per-rate computation and team-target-share tests."""

    def test_yards_per_reception_computation(self, te_player_games_factory):
        df = te_player_games_factory(n_weeks=5, receptions=4, receiving_yards=48)
        _compute_features(df)
        week3 = df[df["week"] == 3]
        # 96 / 8 = 12.0
        assert pytest.approx(week3["yards_per_reception_L3"].iloc[0], abs=0.01) == 12.0

    def test_reception_rate_computation(self, te_player_games_factory):
        df = te_player_games_factory(n_weeks=5, receptions=4, targets=6)
        _compute_features(df)
        week3 = df[df["week"] == 3]
        assert pytest.approx(week3["reception_rate_L3"].iloc[0], abs=0.01) == 4 / 6

    def test_td_rate_per_target_computation(self, te_player_games_factory):
        """TE-specific td_rate_per_target_L3."""
        df = te_player_games_factory(n_weeks=5, receiving_tds=1, targets=6)
        _compute_features(df)
        week3 = df[df["week"] == 3]
        # 2 / 12 = 0.1667
        assert pytest.approx(week3["td_rate_per_target_L3"].iloc[0], abs=0.01) == 1 / 6

    def test_team_target_share_single_player(self, te_player_games_factory):
        """Solo TE on team should have target share close to 1.0."""
        df = te_player_games_factory(n_weeks=5, targets=6, recent_team="KC")
        _compute_features(df)
        later = df[df["week"] >= 3]
        shares = later["team_te_target_share_L3"].dropna()
        # Why: rolling-3 share is defined from week 3 onward (3 weeks >= 3 in a 5-week run)
        assert len(shares) == 3
        # Why: solo TE -> share == 1.0; 1.01 ceiling absorbs float rounding
        assert (shares <= 1.01).all()

    def test_team_target_share_two_players(self, te_player_games_factory):
        """Two TEs on team split target share."""
        p1 = te_player_games_factory("T1", n_weeks=5, targets=5, recent_team="KC")
        p2 = te_player_games_factory("T2", n_weeks=5, targets=5, recent_team="KC")
        df = pd.concat([p1, p2], ignore_index=True)
        _compute_features(df)
        later = df[(df["week"] >= 3) & (df["player_id"] == "T1")]
        shares = later["team_te_target_share_L3"].dropna()
        assert len(shares) == 3
        assert all(0.4 <= s <= 0.6 for s in shares)

    def test_team_target_share_stint_aware_on_trade(self, te_player_games_factory):
        """#1192: the 3-week team-TE-target-share denominator must reset on a
        mid-season trade, not mix the old and new team's TE-target volume.

        TE_A plays weeks 1-4 on KC alongside TE_B (each 6 targets → KC TE
        total = 12/week, share ≈ 0.5), then is traded to SF for weeks 5-7
        where he's the lone TE (share = 1.0). At week 7 the rolling window
        (shift(1) → weeks 5,6) lies entirely inside the SF stint, so the
        stint-aware share is exactly 1.0. The old ``player×season`` grouping
        spanned the trade (window weeks 4,5,6 → player 18 / team 12+6+6=24 =
        0.75) — mirrors the WR test (#674).
        """
        te_a_kc = te_player_games_factory("TE_A", n_weeks=4, targets=6, recent_team="KC")
        te_a_sf = te_player_games_factory("TE_A", n_weeks=3, targets=6, recent_team="SF")
        te_a_sf["week"] = [5, 6, 7]
        te_b_kc = te_player_games_factory("TE_B", n_weeks=4, targets=6, recent_team="KC")
        df = pd.concat([te_a_kc, te_a_sf, te_b_kc], ignore_index=True)
        _compute_features(df)

        a = df[df["player_id"] == "TE_A"].set_index("week")["team_te_target_share_L3"]
        # Stint-aware: window {5,6} fully inside the SF stint → 12/12 = 1.0.
        # (A non-stint denominator would give 18/24 = 0.75, mixing KC's wk4.)
        assert pytest.approx(a.loc[7], abs=1e-9) == 1.0
        # Stint boundary (old→new 0.5→0.0 at week 5): first game of the new
        # stint has no prior-game window inside it → rolling NaN → safe_divide
        # fills 0; week 6 (window {5}) is already all-SF → 1.0.
        assert pytest.approx(a.loc[5], abs=1e-9) == 0.0
        assert pytest.approx(a.loc[6], abs=1e-9) == 1.0


@pytest.mark.unit
class TestFillTENansPriorSeason:
    """#1290: prior_season_mean_catch_rate is whitelisted (INCLUDE_FEATURES
    ["prior_season"]) but absent from _SPECIFIC_FEATURES, so it must be
    carved into the leak-safe train-mean fill — otherwise a rookie /
    no-prior-season TE falls through to build_position_features' catch-all
    .fillna(0), and a raw 0 (vs a ~0.65 league catch rate) maps to a strong
    negative z-score post-scaler. Mirrors the RB fix (#390)."""

    def test_catch_rate_train_mean_filled_not_zero(self):
        train = pd.DataFrame(
            {"feat1": [1.0, 2.0, 3.0], "prior_season_mean_catch_rate": [0.6, 0.8, float("nan")]}
        )
        val = pd.DataFrame({"feat1": [1.5], "prior_season_mean_catch_rate": [float("nan")]})
        test = pd.DataFrame({"feat1": [2.5], "prior_season_mean_catch_rate": [float("nan")]})

        # te_feature_cols deliberately excludes the prior-season column — the
        # pipeline passes only _SPECIFIC_FEATURES here.
        train, val, test = fill_nans(train, val, test, ["feat1"])

        train_mean = 0.7  # mean of the two non-NaN train rows
        assert pytest.approx(train["prior_season_mean_catch_rate"].iloc[2]) == train_mean
        assert pytest.approx(val["prior_season_mean_catch_rate"].iloc[0]) == train_mean
        assert pytest.approx(test["prior_season_mean_catch_rate"].iloc[0]) == train_mean

    def test_carve_out_wiring_matches_production_config(self):
        """Pin the activation preconditions the carve-out silently depends on:
        the column is whitelisted (so the model consumes it), absent from
        _SPECIFIC_FEATURES (so it needs the carve-out at all), and
        _compute_features emits it under exactly this name — a rename or
        whitelist change must fail HERE, not silently re-zero rookies."""
        from src.te.config import POSITION_CONFIG
        from src.te.features import get_feature_columns

        col = "prior_season_mean_catch_rate"
        assert col in get_feature_columns()
        assert col not in POSITION_CONFIG.specific_features
        df = _make_player_games(n_weeks=3)
        df["prior_season_mean_receptions"] = 3.0
        df["prior_season_mean_targets"] = 5.0
        _compute_features(df)
        assert col in df.columns
        assert df[col].notna().all()
